--Esercizio 1
SELECT * FROM DELIVERERS;

--Esercizio 2
SELECT DISTINCT COMPANYID FROM COMPANYDEL;

--Esercizio 3
SELECT NAME, DELIVERERID
FROM DELIVERERS
WHERE NAME LIKE 'B%';

--Esercizio 4
SELECT NAME, SEX, DELIVERERID
FROM DELIVERERS
WHERE PHONENO <> 8467 OR PHONENO IS NULL;

--Esercizio 5
SELECT DISTINCT NAME, TOWN
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID;

--Esercizio 6
SELECT DISTINCT NAME, INITIALS
FROM DELIVERERS D, PENALTIES P, COMPANIES C
WHERE D.DELIVERERID = P.DELIVERERID AND C.DELIVERERID = P.DELIVERERID
AND DATA > TO_DATE ('31/12/1980','DD/MM/YYYY')
ORDER BY NAME;

--Esercizio 7
SELECT DISTINCT COMPANYID, D.DELIVERERID
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID
AND D.TOWN = 'Stratford' 
AND C.NUMDELIVERIES > 0 AND C.NUMCOLLECTIONS > 1;

--Esercizio 8
SELECT DISTINCT D.DELIVERERID
FROM DELIVERERS D, COMPANYDEL C, COMPANIES CO
WHERE D.DELIVERERID = C.DELIVERERID AND CO.COMPANYID = C.COMPANYID
AND YEAR_OF_BIRTH >1962 AND MANDATE = 'first'
ORDER BY D.DELIVERERID DESC;

--Esercizio 9
SELECT DISTINCT NAME
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID
AND (TOWN = 'Stratford' OR TOWN = 'Inglewood')
GROUP BY D.DELIVERERID, NAME
HAVING COUNT(*) > 1;

--Esercizio 10
SELECT D.DELIVERERID, SUM(AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID
AND TOWN = 'Inglewood'
GROUP BY D.DELIVERERID
HAVING COUNT(*) > 1;

--Esercizio 11
SELECT D.NAME, MIN(P.AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID
GROUP BY D.DELIVERERID, D.NAME
HAVING COUNT(*) >= 2 AND COUNT(*) <= 4;

--Esercizio 12
SELECT SUM(NUMDELIVERIES), SUM(NUMCOLLECTIONS)
FROM COMPANYDEL C, DELIVERERS D
WHERE D.DELIVERERID = C.DELIVERERID
AND TOWN <> 'Stratford'
AND NAME LIKE 'B%';
